//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4971
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
//             Created By： Administrator
//             Created Time： 2012/12/31 12:29:19
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>
    /// 实体systemcustomerEntity，对应表systemcustomer
    /// </summary>
    [Serializable()]
    public sealed class systemcustomerEntity : EntityObject
    {
        
        /// <summary>
        /// 对应表字段AutoID
        /// </summary>
        private int m_AutoID = 0;
        
        /// <summary>
        /// 对应表字段Title
        /// </summary>
        private string m_Title = string.Empty;
        
        /// <summary>
        /// 对应表字段Status
        /// </summary>
        private byte m_Status = 0;
        
        /// <summary>
        /// 对应表字段LinkMan
        /// </summary>
        private string m_LinkMan = string.Empty;
        
        /// <summary>
        /// 对应表字段Phone
        /// </summary>
        private string m_Phone = string.Empty;
        
        /// <summary>
        /// 对应表字段MobilePhone
        /// </summary>
        private string m_MobilePhone = string.Empty;
        /// <summary>
        /// 对应表字段Email
        /// </summary>
        private string m_Email = string.Empty;
        /// <summary>
        /// 对应表字段QQ
        /// </summary>
        private string m_QQ = string.Empty;
        
        /// <summary>
        /// 对应表字段Fax
        /// </summary>
        private string m_Fax = string.Empty;
        
        /// <summary>
        /// 对应表字段Address
        /// </summary>
        private string m_Address = string.Empty;
        private int m_ProvinceID = 0;
        private int m_CityID = 0;
        private int m_CountyID = 0;
        private int m_TownID = 0;
        /// <summary>
        /// 对应表字段OrderValue
        /// </summary>
        private int m_OrderValue = 0;
        private int m_OpenStatus = 0;
        /// <summary>
        /// 对应表字段Remark
        /// </summary>
        private string m_Remark = string.Empty;
        
        /// <summary>
        /// 对应表字段CreatorID
        /// </summary>
        private int m_CreatorID = 0;
        
        /// <summary>
        /// 对应表字段CreateDate
        /// </summary>
        private System.DateTime m_CreateDate = DateTime.MinValue;
        
        /// <summary>
        /// 对应表字段Modifier
        /// </summary>
        private int m_Modifier = 0;
        
        /// <summary>
        /// 对应表字段ModifyDate
        /// </summary>
        private System.DateTime m_ModifyDate = DateTime.MinValue;
        
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public systemcustomerEntity()
        {
        }
        
        /// <summary>
        /// 属性AutoID，对应数据库字段AutoID
        /// </summary>
        public int AutoID
        {
            get
            {
                return this.m_AutoID;
            }
            set
            {
                this.m_AutoID = value;
            }
        }
        
        /// <summary>
        /// 属性Title，对应数据库字段Title
        /// </summary>
        public string Title
        {
            get
            {
                return this.m_Title;
            }
            set
            {
                this.m_Title = value;
            }
        }
        
        /// <summary>
        /// 属性Status，对应数据库字段Status
        /// </summary>
        public byte Status
        {
            get
            {
                return this.m_Status;
            }
            set
            {
                this.m_Status = value;
            }
        }
        
        /// <summary>
        /// 属性LinkMan，对应数据库字段LinkMan
        /// </summary>
        public string LinkMan
        {
            get
            {
                return this.m_LinkMan;
            }
            set
            {
                this.m_LinkMan = value;
            }
        }
        
        /// <summary>
        /// 属性Phone，对应数据库字段Phone
        /// </summary>
        public string Phone
        {
            get
            {
                return this.m_Phone;
            }
            set
            {
                this.m_Phone = value;
            }
        }
        
        /// <summary>
        /// 属性MobilePhone，对应数据库字段MobilePhone
        /// </summary>
        public string MobilePhone
        {
            get
            {
                return this.m_MobilePhone;
            }
            set
            {
                this.m_MobilePhone = value;
            }
        }
        
        /// <summary>
        /// 属性QQ，对应数据库字段QQ
        /// </summary>
        public string QQ
        {
            get
            {
                return this.m_QQ;
            }
            set
            {
                this.m_QQ = value;
            }
        }
        
        /// <summary>
        /// 属性Fax，对应数据库字段Fax
        /// </summary>
        public string Fax
        {
            get
            {
                return this.m_Fax;
            }
            set
            {
                this.m_Fax = value;
            }
        }
        
        /// <summary>
        /// 属性Address，对应数据库字段Address
        /// </summary>
        public string Address
        {
            get
            {
                return this.m_Address;
            }
            set
            {
                this.m_Address = value;
            }
        }
        /// <summary>
        /// 属性Email，对应数据库字段Email
        /// </summary>
        public string Email
        {
            get
            {
                return this.m_Email;
            }
            set
            {
                this.m_Email = value;
            }
        } 
        
        public int ProvinceID
        {
            get
            {
                return this.m_ProvinceID;
            }
            set
            {
                this.m_ProvinceID = value;
            }
        }

        public int CityID
        {
            get
            {
                return this.m_CityID;
            }
            set
            {
                this.m_CityID = value;
            }
        }

        public int CountyID
        {
            get
            {
                return this.m_CountyID;
            }
            set
            {
                this.m_CountyID = value;
            }
        }
      
        public int TownID
        {
            get
            {
                return this.m_TownID;
            }
            set
            {
                this.m_TownID = value;
            }
        }
        /// <summary>
        /// 属性OrderValue，对应数据库字段OrderValue
        /// </summary>
        public int OrderValue
        {
            get
            {
                return this.m_OrderValue;
            }
            set
            {
                this.m_OrderValue = value;
            }
        }
        
        /// <summary>
        /// 属性Remark，对应数据库字段Remark
        /// </summary>
        public string Remark
        {
            get
            {
                return this.m_Remark;
            }
            set
            {
                this.m_Remark = value;
            }
        }
        public int OpenStatus
        {
            get
            {
                return this.m_OpenStatus;
            }
            set
            {
                this.m_OpenStatus = value;
            }
        }
        /// <summary>
        /// 属性CreatorID，对应数据库字段CreatorID
        /// </summary>
        public int CreatorID
        {
            get
            {
                return this.m_CreatorID;
            }
            set
            {
                this.m_CreatorID = value;
            }
        }
        
        /// <summary>
        /// 属性CreateDate，对应数据库字段CreateDate
        /// </summary>
        public System.DateTime CreateDate
        {
            get
            {
                return this.m_CreateDate;
            }
            set
            {
                this.m_CreateDate = value;
            }
        }
        
        /// <summary>
        /// 属性Modifier，对应数据库字段Modifier
        /// </summary>
        public int Modifier
        {
            get
            {
                return this.m_Modifier;
            }
            set
            {
                this.m_Modifier = value;
            }
        }
        
        /// <summary>
        /// 属性ModifyDate，对应数据库字段ModifyDate
        /// </summary>
        public System.DateTime ModifyDate
        {
            get
            {
                return this.m_ModifyDate;
            }
            set
            {
                this.m_ModifyDate = value;
            }
        }
        
        /// <summary>
        /// 静态方法，根据主键来获取实体,如果没有获取到则返回null
        /// </summary>
        public static systemcustomerEntity GetEntityByPrimaryKey(int AutoID)
        {
            systemcustomerEntity obj = new systemcustomerEntity();
            obj.AutoID=AutoID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>
        /// 重新OnEuqal方法，通过主键来判断
        /// </summary>
        public override bool Equals(object obj)
        {
            if ((obj == null) || !(obj is systemcustomerEntity))
            {
                return false;
            }
            systemcustomerEntity tmpObj = (systemcustomerEntity)obj;
            if ((this.m_AutoID == tmpObj.m_AutoID))
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        
        /// <summary>
        /// 重新GetHashCode方法，主键的Hash值累积
        /// </summary>
        public override int GetHashCode()
        {
             return this.m_AutoID.GetHashCode();
        }
        
        /// <summary>
        /// 表字段结构，封装了实体对应数据表的所有字段
        /// </summary>
        public struct Columns
        {
            
            /// <summary>
            /// 表字段AutoID
            /// </summary>
            public const string AutoID = "AutoID";
            
            /// <summary>
            /// 表字段Title
            /// </summary>
            public const string Title = "Title";
            
            /// <summary>
            /// 表字段Status
            /// </summary>
            public const string Status = "Status";
            
            /// <summary>
            /// 表字段LinkMan
            /// </summary>
            public const string LinkMan = "LinkMan";
            
            /// <summary>
            /// 表字段Phone
            /// </summary>
            public const string Phone = "Phone";
            
            /// <summary>
            /// 表字段MobilePhone
            /// </summary>
            public const string MobilePhone = "MobilePhone";
            
            /// <summary>
            /// 表字段QQ
            /// </summary>
            public const string QQ = "QQ";
            
            /// <summary>
            /// 表字段Fax
            /// </summary>
            public const string Fax = "Fax";
            
            /// <summary>
            /// 表字段Address
            /// </summary>
            public const string Address = "Address";
            
            /// <summary>
            /// 表字段OrderValue
            /// </summary>
            public const string OrderValue = "OrderValue";
            
            /// <summary>
            /// 表字段Remark
            /// </summary>
            public const string Remark = "Remark";
            
            /// <summary>
            /// 表字段CreatorID
            /// </summary>
            public const string CreatorID = "CreatorID";
            
            /// <summary>
            /// 表字段CreateDate
            /// </summary>
            public const string CreateDate = "CreateDate";
            
            /// <summary>
            /// 表字段Modifier
            /// </summary>
            public const string Modifier = "Modifier";
            
            /// <summary>
            /// 表字段ModifyDate
            /// </summary>
            public const string ModifyDate = "ModifyDate";
            public const string OpenStatus = "OpenStatus";
            public const string Email = "Email"; 

            public const string ProvinceID = "ProvinceID";
            public const string CityID = "CityID";
            public const string CountyID = "CountyID";
            public const string TownID = "TownID";
        }
    }
}
