//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
//             Created By： Jason Wang
//             Created Time： 2013/11/1 14:21:53
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>
    /// 实体webuserEntity，对应表webuser
    /// </summary>
    [Serializable()]
    public sealed class webuserEntity : EntityObject
    {
        
        /// <summary>
        /// 对应表字段AutoID
        /// </summary>
        private int m_AutoID = 0;
        
        /// <summary>
        /// 对应表字段CustomerID
        /// </summary>
        private int m_CustomerID = 0;
        
        /// <summary>
        /// 对应表字段Title
        /// </summary>
        private string m_Title = string.Empty;
        
        /// <summary>
        /// 对应表字段UserPassword
        /// </summary>
        private string m_UserPassword = string.Empty;
        
        /// <summary>
        /// 对应表字段RealName
        /// </summary>
        private string m_RealName = string.Empty;
        
        /// <summary>
        /// 对应表字段IdentityCard
        /// </summary>
        private string m_IdentityCard = string.Empty;
        
        /// <summary>
        /// 对应表字段UserSex
        /// </summary>
        private string m_UserSex = string.Empty;
        
        /// <summary>
        /// 对应表字段Status
        /// </summary>
        private byte m_Status = 0;
        
        /// <summary>
        /// 对应表字段UserEmail
        /// </summary>
        private string m_UserEmail = string.Empty;
        
        /// <summary>
        /// 对应表字段Address
        /// </summary>
        private string m_Address = string.Empty;
        
        /// <summary>
        /// 对应表字段Phone
        /// </summary>
        private string m_Phone = string.Empty;
        
        /// <summary>
        /// 对应表字段MobilePhone
        /// </summary>
        private string m_MobilePhone = string.Empty;
        
        /// <summary>
        /// 对应表字段UserBirthday
        /// </summary>
        private System.DateTime m_UserBirthday=DateTime.MinValue;// DateTime.Parse("2013-01-01");
        
        /// <summary>
        /// 对应表字段CreatorID
        /// </summary>
        private int m_CreatorID = 0;
        
        /// <summary>
        /// 对应表字段CreateDate
        /// </summary>
        private System.DateTime m_CreateDate = DateTime.MinValue;
        
        /// <summary>
        /// 对应表字段Modifier
        /// </summary>
        private int m_Modifier = 0;
        
        /// <summary>
        /// 对应表字段ModifyDate
        /// </summary>
        private System.DateTime m_ModifyDate = DateTime.MinValue;
        
        /// <summary>
        /// 默认构造函数
        /// </summary>
        public webuserEntity()
        {
        }
        
        /// <summary>
        /// 属性AutoID，对应数据库字段AutoID
        /// </summary>
        public int AutoID
        {
            get
            {
                return this.m_AutoID;
            }
            set
            {
                this.m_AutoID = value;
            }
        }
        
        /// <summary>
        /// 属性CustomerID，对应数据库字段CustomerID
        /// </summary>
        public int CustomerID
        {
            get
            {
                return this.m_CustomerID;
            }
            set
            {
                this.m_CustomerID = value;
            }
        }
        
        /// <summary>
        /// 属性Title，对应数据库字段Title
        /// </summary>
        public string Title
        {
            get
            {
                return this.m_Title;
            }
            set
            {
                this.m_Title = value;
            }
        }
        
        /// <summary>
        /// 属性UserPassword，对应数据库字段UserPassword
        /// </summary>
        public string UserPassword
        {
            get
            {
                return this.m_UserPassword;
            }
            set
            {
                this.m_UserPassword = value;
            }
        }
        
        /// <summary>
        /// 属性RealName，对应数据库字段RealName
        /// </summary>
        public string RealName
        {
            get
            {
                return this.m_RealName;
            }
            set
            {
                this.m_RealName = value;
            }
        }
        
        /// <summary>
        /// 属性IdentityCard，对应数据库字段IdentityCard
        /// </summary>
        public string IdentityCard
        {
            get
            {
                return this.m_IdentityCard;
            }
            set
            {
                this.m_IdentityCard = value;
            }
        }
        
        /// <summary>
        /// 属性UserSex，对应数据库字段UserSex
        /// </summary>
        public string UserSex
        {
            get
            {
                return this.m_UserSex;
            }
            set
            {
                this.m_UserSex = value;
            }
        }
        
        /// <summary>
        /// 属性Status，对应数据库字段Status
        /// </summary>
        public byte Status
        {
            get
            {
                return this.m_Status;
            }
            set
            {
                this.m_Status = value;
            }
        }
        
        /// <summary>
        /// 属性UserEmail，对应数据库字段UserEmail
        /// </summary>
        public string UserEmail
        {
            get
            {
                return this.m_UserEmail;
            }
            set
            {
                this.m_UserEmail = value;
            }
        }
        
        /// <summary>
        /// 属性Address，对应数据库字段Address
        /// </summary>
        public string Address
        {
            get
            {
                return this.m_Address;
            }
            set
            {
                this.m_Address = value;
            }
        }
        
        /// <summary>
        /// 属性Phone，对应数据库字段Phone
        /// </summary>
        public string Phone
        {
            get
            {
                return this.m_Phone;
            }
            set
            {
                this.m_Phone = value;
            }
        }
        
        /// <summary>
        /// 属性MobilePhone，对应数据库字段MobilePhone
        /// </summary>
        public string MobilePhone
        {
            get
            {
                return this.m_MobilePhone;
            }
            set
            {
                this.m_MobilePhone = value;
            }
        }
        
        /// <summary>
        /// 属性UserBirthday，对应数据库字段UserBirthday
        /// </summary>
        public System.DateTime UserBirthday
        {
            get
            {
                return this.m_UserBirthday;
            }
            set
            {
                this.m_UserBirthday = value;
            }
        }
        
        /// <summary>
        /// 属性CreatorID，对应数据库字段CreatorID
        /// </summary>
        public int CreatorID
        {
            get
            {
                return this.m_CreatorID;
            }
            set
            {
                this.m_CreatorID = value;
            }
        }
        
        /// <summary>
        /// 属性CreateDate，对应数据库字段CreateDate
        /// </summary>
        public System.DateTime CreateDate
        {
            get
            {
                return this.m_CreateDate;
            }
            set
            {
                this.m_CreateDate = value;
            }
        }
        
        /// <summary>
        /// 属性Modifier，对应数据库字段Modifier
        /// </summary>
        public int Modifier
        {
            get
            {
                return this.m_Modifier;
            }
            set
            {
                this.m_Modifier = value;
            }
        }
        
        /// <summary>
        /// 属性ModifyDate，对应数据库字段ModifyDate
        /// </summary>
        public System.DateTime ModifyDate
        {
            get
            {
                return this.m_ModifyDate;
            }
            set
            {
                this.m_ModifyDate = value;
            }
        }
        
        /// <summary>
        /// 静态方法，根据主键来获取实体,如果没有获取到则返回null
        /// </summary>
        public static webuserEntity GetEntityByPrimaryKey(int AutoID)
        {
            webuserEntity obj = new webuserEntity();
            obj.AutoID=AutoID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>
        /// 重新OnEuqal方法，通过主键来判断
        /// </summary>
        public override bool Equals(object obj)
        {
            if ((obj == null) || !(obj is webuserEntity))
            {
                return false;
            }
            webuserEntity tmpObj = (webuserEntity)obj;
            if ((this.m_AutoID == tmpObj.m_AutoID))
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        
        /// <summary>
        /// 重新GetHashCode方法，主键的Hash值累积
        /// </summary>
        public override int GetHashCode()
        {
             return this.m_AutoID.GetHashCode();
        }
        
        /// <summary>
        /// 表字段结构，封装了实体对应数据表的所有字段
        /// </summary>
        public struct Columns
        {
            
            /// <summary>
            /// 表字段AutoID
            /// </summary>
            public const string AutoID = "AutoID";
            
            /// <summary>
            /// 表字段CustomerID
            /// </summary>
            public const string CustomerID = "CustomerID";
            
            /// <summary>
            /// 表字段Title
            /// </summary>
            public const string Title = "Title";
            
            /// <summary>
            /// 表字段UserPassword
            /// </summary>
            public const string UserPassword = "UserPassword";
            
            /// <summary>
            /// 表字段RealName
            /// </summary>
            public const string RealName = "RealName";
            
            /// <summary>
            /// 表字段IdentityCard
            /// </summary>
            public const string IdentityCard = "IdentityCard";
            
            /// <summary>
            /// 表字段UserSex
            /// </summary>
            public const string UserSex = "UserSex";
            
            /// <summary>
            /// 表字段Status
            /// </summary>
            public const string Status = "Status";
            
            /// <summary>
            /// 表字段UserEmail
            /// </summary>
            public const string UserEmail = "UserEmail";
            
            /// <summary>
            /// 表字段Address
            /// </summary>
            public const string Address = "Address";
            
            /// <summary>
            /// 表字段Phone
            /// </summary>
            public const string Phone = "Phone";
            
            /// <summary>
            /// 表字段MobilePhone
            /// </summary>
            public const string MobilePhone = "MobilePhone";
            
            /// <summary>
            /// 表字段UserBirthday
            /// </summary>
            public const string UserBirthday = "UserBirthday";
            
            /// <summary>
            /// 表字段CreatorID
            /// </summary>
            public const string CreatorID = "CreatorID";
            
            /// <summary>
            /// 表字段CreateDate
            /// </summary>
            public const string CreateDate = "CreateDate";
            
            /// <summary>
            /// 表字段Modifier
            /// </summary>
            public const string Modifier = "Modifier";
            
            /// <summary>
            /// 表字段ModifyDate
            /// </summary>
            public const string ModifyDate = "ModifyDate";
        }
    }
}
